### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by sansho88** [BenJ3D/ft_transcendence#160]
### 1 Overview
  - [x] Backend en NestJS
  - [x]  Frontend en TypeScript
  - [x]  Utiliser des bibliothèques à jour
  - [x]  Base de données PostgreSQL
  - [x]  Site monopage
  - [x]  Compatibilité avec les navigateurs
  - [x]  Pas d'erreurs non gérées
  - [x]  Lancement avec `docker-compose`

### 2 Security concerns
  - [x]  Hachage des mots de passe
  - [x]  Protection contre les injections SQL
  - [x] Validation cote Serveur

### 3 User Account
  - [x]  Authentification via OAuth 42
  - [x]  Choix d'un nom d'utilisateur
  - [x]  Téléchargement d'un avatar
  - [x]  Authentification à deux facteurs
  - [x]  Ajout d'amis
  - [x]  Affichage des statistiques
  - [x]  Historique des matchs

### 4 Chat
  - [x]  Création de canaux (publics, privés, protégés)
  - [x]  Messages directs
  - [x]  Blocage d'utilisateurs / filtrer les messages en consequence
  - [x]  Gestion des canaux
  - [x]  Invitations à jouer à Pong
  - [x]  Accès aux profils
  - [x] Invitation dans les channels prives
  - [x] User admin
  - [X] User owner d'un channel

### 5 Game
  - [x]  Jeu en direct de Pong
  - [x]  Système de matchmaking
  - [x]  Personnalisation du jeu
  - [x]  Responsivité du jeu

**Comment by BenJ3D** [comment]
FINISHED
